### ISSUE TITLE
What impact it will have to adjust the size

### ISSUE THREAD

**Issue by 13331112522** [BCV-Uniandes/DMS#28]
1. How much impact it will have on the mIoU when I adjust size from 512 to 384 or 256 with --size. I got quite lower result compared with your result. The mIoU of the referit val down to 0.47 and unc to 0.36 when I use --size. I am wondering  whether it is reasonable result.

2. I am thinking of using bounding box rather than mask to locate the object with language guide. How could I use your code to train and test that? Is there any suggestions or instructions. 

Appreciated for your efforts to reply

**Comment by andfoy** [comment]
@13331112522 Thanks for the questions, here are some answers:

> How much impact it will have on the mIoU when I adjust size from 512 to 384 or 256 with --size. I got quite lower result compared with your result. The mIoU of the referit val down to 0.47 and unc to 0.36 when I use --size. I am wondering whether it is reasonable result.

The dropdown in performance is due to the evaluation process, in which the resulting segmentation map of DMN (which should be of size 256) is directly upsampled to the image original size (~600px) and then compared against the ground truth. Thus, details are lost, due to the reduction in the receptive field of the CNN neurons.

>  I am thinking of using bounding box rather than mask to locate the object with language guide. How could I use your code to train and test that? Is there any suggestions or instructions.

As segmentation maps contain more information than bounding boxes, you could take the resulting map and compute the enclosing bounding box. Otherwise, major modifications would be required on the original architecture to produce bounding boxes by default, such as removing the upsampling module, and take the Synthesis Module last hidden state to produce box coordinates, which are compared using Smooth-L1 loss in logarithmic space.

**Comment by 13331112522** [comment]
Great thanks for your explanation and suggestion. @andfoy
